### ISSUE TITLE
TPDO inhibitTimer_us / eventTimer_us calculation

### ISSUE THREAD

**Issue by Blazej1994** [CANopenNode/CANopenPIC#10]
Hi

I am currently implementing CanOpenNode on dsPIC33FJ128MC710A based on example_PIC32.X and have found an issue which can be problematic on 16bit devices.

In file CO_PDO.c, function CO_TPDO_init() there is recalculation of inhibit / event Time to resolution of [us] (in my code this are lines 1179, 1180):

TPDO->inhibitTime_us = inhibitTime * 100;
TPDO->eventTime_us = eventTime * 1000; 

and here inhibitTime_us is uint32_t and inhibitTime is uint16_t. Compiler takes number 100 also as uint16_t so we have here:
uint32_t = uint16_t * uint16_t and in case of my compiler result of uint16_t * uint16_t is uint16_t which obviously leads to improper calculation.

Solution of this issue is casting inhibitTime / eventTime to uint32_t like below:

    TPDO->inhibitTime_us = (uint32_t)inhibitTime * 100;
    TPDO->eventTime_us = (uint32_t)eventTime * 1000;

I think it can resolve possible problems on other microcontrolers which has 16bit or 8bit architecture.

**Comment by CANopenNode** [comment]
Yes, you are right. There is a bug. Can you make a pull request?

**Comment by Blazej1994** [comment]
Sure, I will try, I am new on github :). MaybeI should do it in CANopenNode because it is source of this code?

**Comment by CANopenNode** [comment]
Yes, on CANopenNode. Make a fork, edit and send pull request.

**Comment by Blazej1994** [comment]
Ok
