### ISSUE TITLE
Putting CAN Transceiver in Standby Mode

### ISSUE THREAD

**Issue by mjphillips1981** [CANopenNode/CANopenPIC#2]
I know this project has not been worked on for several years.  But I was successful with downloading it and getting it to work in my application.  But I have one question if anyone can help.  I need to put my CAN transceiver in standby mode to bring the average current draw down.  Any idea where I can do this in the code?  I want the transceiver in standby when not transmitting.  Turn on to transmit message on CAN bus and then return to standby.   are there any flags to look for when a message is being sent or finished? Any help would be appreciated.

**Comment by CANopenNode** [comment]
Turn on in CO_CANsend() in CO_driver.c file maybe? Turn off after some delay?

I'm closing it, it is old question.
