### ISSUE TITLE
Document need for heap to be configured for CANopenPIC to work

### ISSUE THREAD

**Issue by follower** [CANopenNode/CANopenPIC#3]
When building a project from scratch it's not documented anywhere (that I could see) that heap needs to be specifically allocated otherwise startup will fail due to an insufficient memory error.

Based on existing project files it seems that a value of `2000` is sufficient.

References:

 * https://github.com/CANopenNode/CANopenPIC/blob/8f72fea5dd56f2392e3cb99380ff69aae491792b/dsPIC33_ex16_IO.X/nbproject/configurations.xml#L153
 * https://github.com/CANopenNode/CANopenPIC/blob/8f72fea5dd56f2392e3cb99380ff69aae491792b/dsPIC33_ex16_IO.X/nbproject/Makefile-default.mk#L259
 * https://github.com/CANopenNode/CANopenPIC/blob/8f72fea5dd56f2392e3cb99380ff69aae491792b/dsPIC33_ex16_IO.X/nbproject/Makefile-default.mk#L264
 * "[Allocating Heap Memory](https://microchipdeveloper.com/mplabx:creating-a-heap)"

**Comment by CANopenNode** [comment]
It is documented now in README.

In CANopen.c is helper variable CO_memoryUsed. To check actual heap usage, it can be read with debugger.
