### ISSUE TITLE
Examples can not be compiled for dsPIC33 with actual CANopenNode

### ISSUE THREAD

**Issue by trojanobelix** [CANopenNode/CANopenPIC#4]
To reproduce
Used this example project 
Compile => ok
Update CANopenNode to actual version (V1.2)

many error, the code might need an update

../../git/CANopenPIC/CANopenNode/CANopen.c:416:13: warning: passing argument 11 of 'CO_EM_init' makes pointer from integer without a cast
../CANopenNode/stack/CO_Emergency.h:392:18: note: expected 'struct CO_CANmodule_t *' but argument is of type 'int'
../../git/CANopenPIC/CANopenNode/CANopen.c:416:13: error: too few arguments to function 'CO_EM_init'
../CANopenNode/stack/CO_Emergency.h:392:18: note: declared here
../../git/CANopenPIC/CANopenNode/CANopen.c:483:17: warning: passing argument 4 of 'CO_RPDO_init' from incompatible pointer type
../CANopenNode/stack/CO_PDO.h:277:18: note: expected 'struct CO_SYNC_t *' but argument is of type 'uint8_t *'
../../git/CANopenPIC/CANopenNode/CANopen.c:483:17: warning: passing argument 5 of 'CO_RPDO_init' makes pointer from integer without a cast
../CANopenNode/stack/CO_PDO.h:277:18: note: expected 'uint8_t *' but argument is of type 'uint8_t'
../../git/CANopenPIC/CANopenNode/CANopen.c:483:17: warning: passing argument 8 of 'CO_RPDO_init' makes integer from pointer without a cast
../CANopenNode/stack/CO_PDO.h:277:18: note: expected 'uint8_t' but argument is of type 'struct CO_RPDOCommPar_t *'
../../git/CANopenPIC/CANopenNode/CANopen.c:483:17: warning: passing argument 9 of 'CO_RPDO_init' from incompatible pointer type
../CANopenNode/stack/CO_PDO.h:277:18: note: expected 'const struct CO_RPDOCommPar_t *' but argument is of type 'struct CO_RPDOMapPar_t *'
../../git/CANopenPIC/CANopenNode/CANopen.c:483:17: warning: passing argument 10 of 'CO_RPDO_init' makes pointer from integer without a cast
../CANopenNode/stack/CO_PDO.h:277:18: note: expected 'const struct CO_RPDOMapPar_t *' but argument is of type 'int16_t'
../../git/CANopenPIC/CANopenNode/CANopen.c:483:17: warning: passing argument 12 of 'CO_RPDO_init' makes integer from pointer without a cast
../CANopenNode/stack/CO_PDO.h:277:18: note: expected 'uint16_t' but argument is of type 'struct CO_CANmodule_t *'
../../git/CANopenPIC/CANopenNode/CANopen.c:483:17: warning: passing argument 13 of 'CO_RPDO_init' makes pointer from integer without a cast
../CANopenNode/stack/CO_PDO.h:277:18: note: expected 'struct CO_CANmodule_t *' but argument is of type 'uint16_t'
../../git/CANopenPIC/CANopenNode/CANopen.c:483:17: error: too few arguments to function 'CO_RPDO_init'
../CANopenNode/stack/CO_PDO.h:277:18: note: declared here
../../git/CANopenPIC/CANopenNode/CANopen.c: In function 'CO

**Comment by CANopenNode** [comment]
It is updated to the latest version, branch split-driver. Just use `git submodule update`
It works now for all three examples. PIC32 and dsPIC33 also tested on Explorer16 board.
