### ISSUE TITLE
Compiling sample project example_dsPIC33_ex16_IO

### ISSUE THREAD

**Issue by Ferrigno1972** [CANopenNode/CANopenPIC#9]
Hi,
I'm new on CanOpen so I decided to build on MPLABX "example_dsPIC33_ex16_IO" project in order to understand how it works

I followed all steps in order to clone from repository, up-date and all,
but when I try to compile I get some errors.

OD_CANNodeID
OD_CANBitRate
CO_OD_RAM
CO_OD_EEPROM
CO_OD_ROM
OD_powerOnCounter
OD_writeOutput8Bit

and many others seems not defined

Where Are these macro? Do I need to define them on a custom application or am I miss something?
Could you please help me to undestand where is my mistake?
If it helps, I attached a screenshot of the basic project

Thank you in advance for your help!

![screenshot](https://user-images.githubusercontent.com/98538279/151386868-7c97349a-7c2f-4379-be59-94fa678d34cb.png)

**Comment by Blazej1994** [comment]
Hi

I have the same problem.
Did you maybe solve it somehow?

**Comment by Ferrigno1972** [comment]
No, I didn't
I'm not working on this topic at the moment

**Comment by CANopenNode** [comment]
dsPIC33 is still on TODO list. Some effort was made in pull request above, which I didn't have time to manage yet.

**Comment by CANopenNode** [comment]
Finally solved, see #12
